[Unity3D-sdk] Fix isVRSupported error in Unity 5
This commit fixes the compile errors:
- Unity 5.0: ```Assets/PocoSDK/VRSupport.cs(42,44): error CS0234: The type or namespace name `VR' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?```
- Unity 5.1-5.3: ```Assets/PocoSDK/VRSupport.cs(42,58): error CS0117: `UnityEngine.VR.VRSettings' does not contain a definition for `loadedDeviceName'```

Property UnityEngine.VR.VRSettings.loadedDeviceName was released in Unity 5.4: https://docs.unity3d.com/540/Documentation/ScriptReference/VR.VRSettings-loadedDeviceName.html